// Opt-in Windows regression: every mutation is confined to a new, private,
// random HKCU\\Software test key owned by this process and removed on exit.
#include <Windows.h>
#include <QCoreApplication>
#include <QUuid>
#include <atomic>
#include <cstring>
#include <iostream>

namespace hooks {
bool unavailable = false, failCommit = false;
int deletions = 0, failDelete = 0, injectDelete = 0, invalidBindings = 0;
bool addChild = false;
HKEY external = nullptr;
LSTATUS lateStatus = ERROR_INVALID_STATE;
std::atomic_bool* cancel = nullptr;
}
BOOL WINAPI deniedCommit(HANDLE) { SetLastError(ERROR_TRANSACTIONAL_CONFLICT); return FALSE; }
HMODULE WINAPI testLoadLibraryExW(LPCWSTR name, HANDLE file, DWORD flags)
{
    if (hooks::unavailable && std::wcscmp(name, L"KtmW32.dll") == 0) {
        SetLastError(ERROR_MOD_NOT_FOUND); return nullptr;
    }
    return LoadLibraryExW(name, file, flags);
}
FARPROC WINAPI testGetProcAddress(HMODULE module, LPCSTR name)
{
    if (hooks::failCommit && std::strcmp(name, "CommitTransaction") == 0) {
        auto function = &deniedCommit;
        FARPROC result = nullptr;
        static_assert(sizeof(function) == sizeof(result));
        std::memcpy(&result, &function, sizeof(result));
        return result;
    }
    return GetProcAddress(module, name);
}
LSTATUS WINAPI testRegOpenKeyTransactedW(HKEY key, LPCWSTR name, DWORD options,
    REGSAM access, PHKEY result, HANDLE transaction, PVOID extra)
{
    if ((name && std::wcschr(name, L'\\')) || options != 0) ++hooks::invalidBindings;
    return RegOpenKeyTransactedW(key, name, options, access, result, transaction, extra);
}
LSTATUS WINAPI testRegDeleteKeyTransactedW(HKEY parent, LPCWSTR name, REGSAM view,
    DWORD reserved, HANDLE transaction, PVOID extra)
{
    ++hooks::deletions;
    if (hooks::deletions == hooks::injectDelete) {
        if (hooks::addChild) {
            HKEY late = nullptr;
            hooks::lateStatus = RegCreateKeyExW(hooks::external, L"LateChild", 0, nullptr,
                REG_OPTION_NON_VOLATILE, KEY_READ, nullptr, &late, nullptr);
            if (late) RegCloseKey(late);
        } else {
            const BYTE bytes[] = {0x91, 0x37};
            hooks::lateStatus = RegSetValueExW(hooks::external, L"Late", 0, REG_BINARY, bytes, sizeof(bytes));
        }
    }
    if (hooks::deletions == hooks::failDelete) return ERROR_ACCESS_DENIED;
    const LSTATUS status = RegDeleteKeyTransactedW(parent, name, view, reserved, transaction, extra);
    if (hooks::cancel) hooks::cancel->store(true);
    return status;
}
#define LoadLibraryExW testLoadLibraryExW
#define GetProcAddress testGetProcAddress
#define RegOpenKeyTransactedW testRegOpenKeyTransactedW
#define RegDeleteKeyTransactedW testRegDeleteKeyTransactedW
#include "../Ksword5.1/Ksword5.1/RegistryDock/RegistryDocumentApply.cpp"
#include "../Ksword5.1/Ksword5.1/RegistryDock/RegistryDocumentApply.Win32.cpp"
#undef LoadLibraryExW
#undef GetProcAddress
#undef RegOpenKeyTransactedW
#undef RegDeleteKeyTransactedW

namespace {
int checks = 0, failures = 0;
void check(bool ok, const char* label)
{
    ++checks;
    if (!ok) { ++failures; std::cerr << "FAIL " << label << '\n'; }
}
const QString prefix = QStringLiteral("Software\\KSwordRegistryTxnRegression_");
struct OwnedRoot {
    QString sub = prefix + QUuid::createUuid().toString(QUuid::Id128);
    QString path = QStringLiteral("HKEY_CURRENT_USER\\") + sub;
    HKEY key = nullptr;
    explicit OwnedRoot(bool volatileKey = false)
    {
        DWORD disposition = 0;
        const LSTATUS status = RegCreateKeyExW(HKEY_CURRENT_USER, reinterpret_cast<LPCWSTR>(sub.utf16()),
            0, nullptr, volatileKey ? REG_OPTION_VOLATILE : REG_OPTION_NON_VOLATILE,
            KEY_ALL_ACCESS, nullptr, &key, &disposition);
        check(status == ERROR_SUCCESS && disposition == REG_CREATED_NEW_KEY, "fresh owned fixture root");
        if (status != ERROR_SUCCESS || disposition != REG_CREATED_NEW_KEY) std::abort();
        const BYTE value = 0x42;
        check(RegSetValueExW(key, L"Original", 0, REG_BINARY, &value, 1) == ERROR_SUCCESS, "fixture original value");
        HKEY leaf = nullptr;
        check(RegCreateKeyExW(key, L"Branch\\Leaf", 0, nullptr, volatileKey ? REG_OPTION_VOLATILE : REG_OPTION_NON_VOLATILE,
            KEY_ALL_ACCESS, nullptr, &leaf, nullptr) == ERROR_SUCCESS, "fixture nested subtree");
        if (leaf) RegCloseKey(leaf);
    }
    ~OwnedRoot()
    {
        RegCloseKey(key);
        // Never clean up a path not generated by this fixture.
        if (!sub.startsWith(prefix) || sub.size() != prefix.size() + 32) std::abort();
        const LSTATUS status = RegDeleteTreeW(HKEY_CURRENT_USER, reinterpret_cast<LPCWSTR>(sub.utf16()));
        check(status == ERROR_SUCCESS || status == ERROR_FILE_NOT_FOUND, "owned fixture cleanup");
    }
    bool exists(const QString& suffix = {}) const
    {
        HKEY opened = nullptr;
        const QString name = sub + suffix;
        const LSTATUS status = RegOpenKeyExW(HKEY_CURRENT_USER, reinterpret_cast<LPCWSTR>(name.utf16()),
            0, KEY_READ, &opened);
        if (opened) RegCloseKey(opened);
        return status == ERROR_SUCCESS;
    }
    bool original() const
    {
        BYTE data = 0; DWORD size = 1, type = 0;
        return RegQueryValueExW(key, L"Original", nullptr, &type, &data, &size) == ERROR_SUCCESS
            && type == REG_BINARY && size == 1 && data == 0x42 && exists(QStringLiteral("\\Branch\\Leaf"));
    }
    RegistryApplyPlan plan(int view = 0) const
    {
        RegistryApplyPlan result; result.viewBits = view;
        RegistryApplyOperation op;
        op.kind = RegistryApplyOperation::Kind::DeleteTree; op.keyPath = path; op.keyExistedBefore = true;
        QString error;
        check(RegistryDocumentService::captureWin32(path, view, op.beforeTree, error), "capture real original subtree");
        result.operations.append(op);
        return result;
    }
};
void reset(OwnedRoot& root)
{
    hooks::unavailable = hooks::failCommit = hooks::addChild = false;
    hooks::deletions = hooks::failDelete = hooks::injectDelete = 0;
    hooks::external = root.key; hooks::cancel = nullptr; hooks::lateStatus = ERROR_INVALID_STATE;
}
}
int main(int argc, char** argv)
{
    QCoreApplication application(argc, argv);
    bool unsupported = false;
    {
        OwnedRoot root; reset(root);
        ApplyTransaction transaction; QString error;
        check(transaction.begin(root.path, error), "real KTM transaction creation");
        HKEY probe = nullptr;
        const LSTATUS status = RegOpenKeyTransactedW(HKEY_CURRENT_USER,
            reinterpret_cast<LPCWSTR>(root.sub.utf16()), 0, KEY_READ, &probe, transaction.handle, nullptr);
        if (probe) RegCloseKey(probe);
        unsupported = status == ERROR_RM_NOT_ACTIVE || status == ERROR_NOT_SUPPORTED;
        if (unsupported) {
            RegistryApplyResult result;
            check(!RegistryDocumentApplyService::applyWin32(root.plan(), result)
                && !result.completed && hooks::deletions == 0 && root.original(),
                "unsupported real resource manager retains the full subtree without fallback");
            std::cout << "NATIVE_TXR_SCENARIOS_SKIPPED=" << status << '\n';
        } else check(status == ERROR_SUCCESS, "native registry resource manager supports transactions");
    }
    if (unsupported) {
        std::cout << "REGISTRY_DOCUMENT_WIN32_CHECKS=" << checks << " FAILURES=" << failures << '\n';
        return failures ? 1 : 0;
    }
    for (int view : {0, 32, 64}) {
        OwnedRoot root; reset(root); RegistryApplyResult result;
        const bool ok = RegistryDocumentApplyService::applyWin32(root.plan(view), result);
        if (!ok) std::cerr << "BASELINE_ERROR=" << result.error.toStdString() << " DELETIONS=" << hooks::deletions << '\n';
        check(ok && result.completed && !root.exists(), "real transaction commits the requested subtree deletion");
    }
    {
        OwnedRoot root; reset(root); RegistryApplyResult result;
        hooks::unavailable = true;
        check(!RegistryDocumentApplyService::applyWin32(root.plan(), result)
            && hooks::deletions == 0 && root.original(), "missing KTM refuses deletion without fallback");
    }
    {
        OwnedRoot root; reset(root); RegistryApplyResult result;
        hooks::failDelete = 2;
        check(!RegistryDocumentApplyService::applyWin32(root.plan(), result)
            && root.original(), "API failure rolls back earlier staged child deletions");
    }
    {
        OwnedRoot root; reset(root); RegistryApplyResult result;
        hooks::failCommit = true;
        check(!RegistryDocumentApplyService::applyWin32(root.plan(), result)
            && hooks::deletions == 3 && root.original(), "commit failure retains the entire original subtree");
    }
    {
        OwnedRoot root; reset(root); RegistryApplyResult result;
        std::atomic_bool cancel {false}; hooks::cancel = &cancel;
        check(!RegistryDocumentApplyService::applyWin32(root.plan(), result, &cancel)
            && result.canceled && root.original(), "cancellation rolls back staged deletion");
    }
    for (int inject : {1, 3}) {
        for (bool child : {false, true}) {
            OwnedRoot root; reset(root); RegistryApplyResult result;
            hooks::injectDelete = inject; hooks::addChild = child;
            const bool ok = RegistryDocumentApplyService::applyWin32(root.plan(), result);
            DWORD size = 0;
            const bool latePresent = child ? root.exists(QStringLiteral("\\LateChild"))
                : RegQueryValueExW(root.key, L"Late", nullptr, nullptr, nullptr, &size) == ERROR_SUCCESS;
            std::cout << "RACE_AT=" << inject << " CHILD=" << child << " WRITER_STATUS=" << hooks::lateStatus
                << " APPLY_OK=" << ok << " LATE_PRESENT=" << latePresent << '\n';
            check(hooks::lateStatus == ERROR_SUCCESS || hooks::lateStatus == ERROR_TRANSACTIONAL_CONFLICT,
                "external writer has a valid success or transaction-conflict result");
            check(hooks::lateStatus != ERROR_SUCCESS || (!ok && latePresent && root.original()),
                "successful late writer is preserved and our whole deletion rolls back");
            check(!ok || hooks::lateStatus != ERROR_SUCCESS, "deletion never succeeds after erasing a successful late write");
        }
    }
    check(hooks::invalidBindings == 0, "transaction binds exact handles and verifies relative leaves with reserved options zero");
    std::cout << "REGISTRY_DOCUMENT_WIN32_CHECKS=" << checks << " FAILURES=" << failures << '\n';
    return failures ? 1 : 0;
}
